// TYPES
export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS';
export const CREATE_PROPERTIES_SUCCESS = 'CREATE_PROPERTIES_SUCCESS';
export const DELETE_PROPERTIES_SUCCESS = 'DELETE_PROPERTIES_SUCCESS';
export const PROPERTIES_ERROR = 'PROPERTIES_ERROR';