// TYPES
export const GET_PROPETIES_SUCCESS = 'GET_PROPETIES_SUCCESS';
export const CREATE_PROPETIES_SUCCESS = 'CREATE_PROPETIES_SUCCESS';
export const DELETE_PROPETIES_SUCCESS = 'DELETE_PROPETIES_SUCCESS';
export const PROPETIES_ERROR = 'PROPETIES_ERROR';